### ISSUE TITLE
Must do maximize to set focus on UI element with MacOS X 10.8.4 after system update.

### ISSUE THREAD

**Issue by miroslavhruz** [agirbal/umongo#150]
Before system update, umongo worked perfectly for me. After doing this update 10.8.4 and change version of java to 1.7.25 (dont know if java version changed or update changed), UI freeze with no response for click on whatever item, only when i click on maximize button it refreshes itself and gave me focus. Do you understand what is my problem? Application is not usable at all.

I have Early 2011 MacBook Pro.

I have 1.4.2 version, run from console gave me this output:

bash-3.2$ ./JavaApplicationStub 
Jun 23, 2013 10:11:19 PM com.edgytech.umongo.UMongo initialize
SEVERE: null
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
    at java.lang.Integer.parseInt(Integer.java:470)
    at java.lang.Integer.parseInt(Integer.java:499)
    at com.edgytech.swingfast.XmlUnit.xmlLoadAttr(XmlUnit.java:1318)
    at com.edgytech.swingfast.XmlUnit.xmlLoadStarAttrs(XmlUnit.java:1515)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:900)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:807)
    at com.edgytech.swingfast.XmlUnit.xmlLoadChildren(XmlUnit.java:1223)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:906)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:807)
    at com.edgytech.swingfast.XmlUnit.xmlLoadChildren(XmlUnit.java:1223)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:906)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:807)
    at com.edgytech.swingfast.XmlUnit.xmlLoadChildren(XmlUnit.java:1223)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:906)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:807)
    at com.edgytech.swingfast.XmlUnit.xmlLoadChildren(XmlUnit.java:1223)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:906)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:807)
    at com.edgytech.swingfast.XmlUnit.xmlLoadChildren(XmlUnit.java:1223)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:906)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:807)
    at com.edgytech.swingfast.XmlUnit.xmlLoadChildren(XmlUnit.java:1223)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:906)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:807)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:962)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:972)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:968)
    at com.edgytech.umongo.UMongo.loadSettings(UMongo.java:104)
    at com.edgytech.umongo.UMongo.initialize(UMongo.java:122)
    at com.edgytech.swingfast.Application$1.run(Application.java:65)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Jun 23, 2013 10:11:35 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: Text of id null: Unit already has a parent com.edgytech.umongo.ConnectDialog of id connectDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:35 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: DynamicComboBox of id uri: Unit already has a parent com.edgytech.umongo.ConnectDialog of id connectDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:35 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: Text of id null: Unit already has a parent com.edgytech.umongo.ConnectDialog of id connectDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:35 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: DynamicComboBox of id servers: Unit already has a parent com.edgytech.umongo.ConnectDialog of id connectDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:35 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: TextField of id databases: Unit already has a parent com.edgytech.umongo.ConnectDialog of id connectDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:35 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: Div of id connectionPool: Unit already has a parent com.edgytech.umongo.ConnectDialog of id connectDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:35 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: Div of id connection: Unit already has a parent com.edgytech.umongo.ConnectDialog of id connectDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:35 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: Div of id proxy: Unit already has a parent com.edgytech.umongo.ConnectDialog of id connectDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:40 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: Text of id null: Unit already has a parent ProgressDialog of id connectProgressDialog, trying to set new parent Div of id null
Jun 23, 2013 10:11:40 PM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: ProgressBar of id progressBar: Unit already has a parent ProgressDialog of id connectProgressDialog, trying to set new parent Div of id null

**Comment by heyarny** [comment]
Hi, I'm having the same issue.
Done the apple update and umongo stopped working.
I even installed the latest oracle java 7 jdk/jre on osx, but didn't help.
Using OSX 10.8.4

**Comment by agirbal** [comment]
thanks for report.
very annoying that they broke smthing, I guess will have to upgrade myself and figure it out..

**Comment by agirbal** [comment]
I have upgraded to OSX 10.8.4 and java 1.7u25.
So far everything works fine for me.
Do you have an easy way to reproduce the issue? At which point exactly does the application become unresponsive?

**Comment by heyarny** [comment]
it simply doesn't react.
Not sure how to check what exactly is causing it.
After a startup the window stays blank white and nothing is happening.
On maximize button the window gets one single redraw update.

Sometimes the console prints that strange debug infos

Jun 25, 2013 2:04:16 AM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: TabbedDiv of id optionTabs: Unit already has a parent com.edgytech.umongo.AppPreferences of id prefDialog, trying to set new parent Div of id null
Jun 25, 2013 2:04:16 AM com.edgytech.swingfast.XmlUnit logDebugLine
INFO: Text of id null: Unit already has a parent com.edgytech.umongo.AppPreferences of id prefDialog, trying to set new parent Div of id null
Jun 25, 2013 2:04:16 AM com.edgytech.swingfast.XmlUnit addChild
WARNING: Duplicate ids 'general' for unit 'com.edgytech.swingfast.Div', only 1st child will exists
Jun 25, 2013 2:04:17 AM com.edgytech.swingfast.XmlUnit addChild
WARNING: Duplicate ids 'advanced' for unit 'com.edgytech.swingfast.Div', only 1st child will exists
...

**Comment by heyarny** [comment]
I downgraded to java 6 again, but the problem persists.

java -version
java version "1.6.0_51"
Java(TM) SE Runtime Environment (build 1.6.0_51-b11-456-11M4508)
Java HotSpot(TM) 64-Bit Server VM (build 20.51-b01-456, mixed mode)

**Comment by heyarny** [comment]
does umongo have a verbose mode?
maybe it can deliver you more details on whats happening there

**Comment by agirbal** [comment]
if the UI just hangs it's going to be tough to debug even with verbose mode :(
Is the CPU high during that time?
Could you try downloading a fresh 1.4.2 umongo and trying?

**Comment by miroslavhruz** [comment]
I've downloaded fresh umongo 1.4.2 on OSX 10.8.2 on my collegue's computer, ran from console and he has not those strange INFO logs with null parent component.

**Comment by agirbal** [comment]
the strange INFO logs are benign, you should be seeing them.
It sounds like the last apple update did something to your computer.. Could you make sure all updates are installed (see from the app store) and restart the computer?
If it still doesnt work, could you attach a screen capture?
thx

**Comment by heyarny** [comment]
- using the last 1.4.2
- all apple updates installed

![screen shot 2013-06-27 at 19 06 14](https://f.cloud.github.com/assets/821278/717411/ed283622-df4b-11e2-9695-1efe7346bc45.png)

**Comment by heyarny** [comment]
I guess this is related to all swing applications.
Check this https://discussions.apple.com/thread/5117371?start=0&tstart=0
I guess you can close this issue by now.

**Comment by heyarny** [comment]
By the way, this solution worked for me at http://www.mathworks.com/matlabcentral/answers/79489#answer_89503

# 

Another method for OS X 10.7/10.8:

Note that this may also remove any other versions of Java installed alongside 1.6

Download Java 2013-003 from http://apple-java-for-mac.en.softonic.com/mac/download

In Terminal, copy and paste these 3 commands to remove enough of the new Java version to allow re-installation of Java 1.6.0_45:

sudo rm -rf /System/Library/Java/JavaVirtualMachines
sudo rm -rf /System/Library/Frameworks/JavaVM.framework
sudo pkgutil --forget com.apple.pkg.JavaForMacOSX107
Then open the downloaded disk image and install JavaForOSX.pkg

You will now need to turn off automatic system updates, and refrain from installing the 2013-004 update when it gets offered again via the App Store.

**Comment by agirbal** [comment]
why is apple messing up with the AWT event thread??
Anyway there is now a new fix by apple:
http://lists.apple.com/archives/java-dev/2013/Jun/msg00055.html
