### ISSUE TITLE
Getting java.lang.IndexOutOfBoundsException error during csv import

### ISSUE THREAD

**Issue by lforge** [agirbal/umongo#224]
I am new to this tool.  I just create a new Collection and try to import some data via csv.  I am getting the following error.

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.RangeCheck(ArrayList.java:547)
    at java.util.ArrayList.get(ArrayList.java:322)
    at com.edgytech.umongo.DocumentDeserializer.fillInTemplate(DocumentDeserializer.java:312)
    at com.edgytech.umongo.DocumentDeserializer.readObject(DocumentDeserializer.java:232)
    at com.edgytech.umongo.CollectionPanel$11.doRun(CollectionPanel.java:969)
    at com.edgytech.umongo.DbJob$1.doInBackground(DbJob.java:84)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:277)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at javax.swing.SwingWorker.run(SwingWorker.java:316)
    at com.edgytech.swingfast.ScalableThreadPool$ScalableThreadpoolWorker.run(ScalableThreadPool.java:48)
    at java.lang.Thread.run(Thread.java:695)

I have listed the first few records in my csv file below.  As you can see, my suspicion is that my last data field lastplayeddate may not always contain data.  So I think that this may have caused your program to fail to import.  I even put in a Template like the following:

{ "membershipno" : "$membershipno/String" , "name" : "$name/String" , "rating" : "$rating/Long", "state":"$state/String","zip":"$zip/String", "birthday":"$birthday/String", "sex":"$sex/String", "expiredate":"$expiredate/String", "lastplayeddate":"$lastplayeddate/String"}

It is still giving me the java.lang.IndexOutOfBounds error.  Do you have any idea why this is the case please?  I am kind of new to MongoDB.  This is one reason why I like your tool.  So if you can let me know if there is something wrong with the data or there is an unhandled issue in uMongo please?  Any assistance is very much appreciated.  Thanks.

==== Data file examples ===
membershipno,name,rating,state,zip,birthday,sex,expiredate,lastplayeddate
3,"Worley, Carol E.",0,"SC","29171","**_","F","3/31/1995",
4,"Worley, Adric E.",0,"SC","29171","**_","M","3/31/1995",
5,"Worley, Aliana E.",0,"SC","29171","**_","F","3/31/1995",
7,"Andrade, John",0,"PA","18512-2437","**_","M","3/31/1995",
8,"Grande, Frank",0,"PA","19087","**_","M","3/31/1995",
9,"Simpson, Mark",0,"VA","24018","**_","F","3/31/1995",
10,"Tanenbaum, Alan",0,"PA","19151","**_","M","3/31/1995",
11,"Sloan, Richard J.",0,"NJ","07731","**_","M","3/31/1995",
12,"Rodriguez, Joel",1064,"PA","17404","***","M","3/31/1996","2/11/1995"

**Comment by lforge** [comment]
Any input on this???  Thanks.

**Comment by lforge** [comment]
Still no update on this?  Is there other support venue that I can post question about this?  Any help will be appreciated.  Thanks.

**Comment by mrlinton** [comment]
Also receiving this, any help would be appreciated

**Comment by agirbal** [comment]
sorry for the delay, I will fix this over weekend. Thanks for patience!

**Comment by agirbal** [comment]
There were 2 issues related to quoted strings. Fixed now
