### ISSUE TITLE
unable to connect to mongodb

### ISSUE THREAD

**Issue by arubygit** [agirbal/umongo#243]
I'm using the default values localhost:27017 and it throws the following exception. Any suggestions?

com.mongodb.MongoTimeoutException: Timed out while waiting to connect after 1999 ms
    at com.mongodb.BaseCluster.getDescription(BaseCluster.java:114)
    at com.mongodb.DBTCPConnector.getClusterDescription(DBTCPConnector.java:396)
    at com.mongodb.DBTCPConnector.getAddress(DBTCPConnector.java:327)
    at com.mongodb.Mongo.getAddress(Mongo.java:473)
    at com.edgytech.umongo.MongoPanel.updateComponentCustom(MongoPanel.java:100)
    at com.edgytech.umongo.MongoPanel.updateComponentCustom(MongoPanel.java:40)
    at com.edgytech.swingfast.XmlComponentUnit.updateComponent(XmlComponentUnit.java:242)
    at com.edgytech.swingfast.XmlJComponentUnit.updateComponent(XmlJComponentUnit.java:51)
    at com.edgytech.swingfast.XmlComponentUnit.updateComponent(XmlComponentUnit.java:260)
    at com.edgytech.umongo.Workspace.setContent(Workspace.java:44)
    at com.edgytech.umongo.UMongo.displayElement(UMongo.java:198)
    at com.edgytech.umongo.UMongo.displayNode(UMongo.java:243)
    at com.edgytech.umongo.BaseTreeNode.handleNodeSelection(BaseTreeNode.java:124)
    at com.edgytech.swingfast.Tree.valueChanged(Tree.java:195)
    at javax.swing.JTree.fireValueChanged(JTree.java:2820)
    at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3191)
    at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:629)
    at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1078)
    at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:287)
    at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:170)
    at javax.swing.JTree.setSelectionPath(JTree.java:1598)
    at com.edgytech.swingfast.Tree.selectNode(Tree.java:275)
    at com.edgytech.swingfast.Tree.selectNode(Tree.java:269)
    at com.edgytech.umongo.UMongo.addMongoClient(UMongo.java:173)
    at com.edgytech.umongo.MainMenu$2.doInBackground(MainMenu.java:222)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:277)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at javax.swing.SwingWorker.run(SwingWorker.java:316)
    at com.edgytech.swingfast.ScalableThreadPool$ScalableThreadpoolWorker.run(ScalableThreadPool.java:48)
    at java.lang.Thread.run(Thread.java:695)

**Comment by agirbal** [comment]
it means umongo can't connect to mongo on localhost, are you sure it's running local on default port?
If you start the mongo shell on the same box, does it connect fine?
Can you try to connect on 127.0.0.1:27017 instead?

**Comment by arubygit** [comment]
Thanks for the advice....It works now....nice interface
