### ISSUE TITLE
when adding shard as replica set, seems the tree node is not populated

### ISSUE THREAD

**Issue by agirbal** [agirbal/umongo#31]

**Comment by agirbal** [comment]
WARNING: null
java.lang.NumberFormatException: For input string: "27017,localhost:27019,localhost:27018"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:481)
    at java.lang.Integer.parseInt(Integer.java:514)
    at org.mongo.jmongob.RouterNode.populateChildren(RouterNode.java:54)
    at org.mongo.jmongob.BaseTreeNode.structureComponentCustom(BaseTreeNode.java:29)
    at org.mongo.jmongob.BaseTreeNode.structureComponentCustom(BaseTreeNode.java:22)
    at com.edgytech.swingfast.XmlComponentUnit.structureComponent(XmlComponentUnit.java:221)
    at com.edgytech.swingfast.XmlComponentUnit.getComponent(XmlComponentUnit.java:187)
    at com.edgytech.swingfast.XmlJComponentUnit.getComponent(XmlJComponentUnit.java:77)
    at com.edgytech.swingfast.XmlJComponentUnit.getComponent(XmlJComponentUnit.java:20)
    at com.edgytech.swingfast.TreeNodeLabel.structureComponentCustom(TreeNodeLabel.java:91)
    at org.mongo.jmongob.BaseTreeNode.structureComponentCustom(BaseTreeNode.java:33)
    at org.mongo.jmongob.BaseTreeNode.structureComponentCustom(BaseTreeNode.java:22)
    at com.edgytech.swingfast.XmlComponentUnit.structureComponent(XmlComponentUnit.java:221)
    at com.edgytech.swingfast.XmlComponentUnit.getComponent(XmlComponentUnit.java:187)
    at com.edgytech.swingfast.XmlJComponentUnit.getComponent(XmlJComponentUnit.java:77)
    at com.edgytech.swingfast.XmlJComponentUnit.getComponent(XmlJComponentUnit.java:20)
    at com.edgytech.swingfast.TreeNodeLabel.structureComponentCustom(TreeNodeLabel.java:91)
    at com.edgytech.swingfast.TreeNodeLabel.structureComponentCustom(TreeNodeLabel.java:19)
    at com.edgytech.swingfast.XmlComponentUnit.structureComponent(XmlComponentUnit.java:221)
    at org.mongo.jmongob.JMongoBrowser.addMongo(JMongoBrowser.java:146)
    at org.mongo.jmongob.MainMenu.connect(MainMenu.java:121)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
