### ISSUE TITLE
java.awt.HeadlessException at startup

### ISSUE THREAD

**Issue by agirbal** [agirbal/umongo#51]
from hyperrjas:

I use rails 3.1 with MongoDb and Mongoid in ubuntu maverick 10.10.

This is my report in console when I run ./launchJMongoBrowser.sh or double click in sh file:

Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
at com.edgytech.swingfast.ButtonBase.xmlPostLoadComponentCallback(ButtonBase.java:344)
at com.edgytech.swingfast.XmlComponentUnit.xmlPostLoadCallback(XmlComponentUnit.java:423)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:903)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:953)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:963)
at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:959)
at org.mongo.jmongob.JMongoBrowser.load(JMongoBrowser.java:85)
at org.mongo.jmongob.JMongoBrowser.initialize(JMongoBrowser.java:111)
at com.edgytech.swingfast.Application$1.run(Application.java:64)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:226)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:647)
at java.awt.EventQueue.access$000(EventQueue.java:96)
at java.awt.EventQueue$1.run(EventQueue.java:608)
at java.awt.EventQueue$1.run(EventQueue.java:606)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:105)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:617)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
Caused by: java.awt.HeadlessException
at sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:231)
at com.edgytech.swingfast.ButtonBase$KeyModifier.(ButtonBase.java:236)
... 54 more

This is report when I run sudo update-java-alternatives -l:

java-6-openjdk 1061 /usr/lib/jvm/java-6-openjdk

Thanks!

Thank you agirbal, Im not runing since server. Im runing the .sh since desktop like admin from my pc. I have ubuntu maverick desktop. I have not ubuntu server.

I need a new version Java? My current version is java-6-openjdk.

I have ubuntu 10.10 maverick in vmware. If you help me for fix this error any help would be appreciated.

Thank you

**Comment by agirbal** [comment]
This is probably a problem with your java installation or with you vmware display setup.
Some information are here:
http://stackoverflow.com/questions/5362512/unable-to-run-java-gui-programs-with-ubuntu

You should try to purge and reinstall java:
sudo apt-get purge openjdk-6-jre openjdk-6-jdk
sudo apt-get install openjdk-6-jre

If that still does not work you need to look for information on that Java exception with vmware.

**Comment by hyperrjas** [comment]
Thank you. Now working fine. The problem was for me run this command:

 sudo apt-get install openjdk-6-jre

Thank you agirbal
