### ISSUE TITLE
OS X says umongo.app is damaged and cannot be started

### ISSUE THREAD

**Issue by psysp** [agirbal/umongo#82]
Hi 
when I try to run umongo on OS X it tells me that the application is defekt and that I should remove it. 

I tired umongo  1.2.1 and 1.2.0

Any ideas who solve this issue?

**Comment by Furizaa** [comment]
+1

**Comment by Furizaa** [comment]
Download the Linux version instead. Extract and run `launch-umongo.sh` from the terminal.

**Comment by psysp** [comment]
Thanks, I will try that.

**Comment by agirbal** [comment]
which osx version do you use?
It opens fine with my 10.7.5.
thanks

**Comment by donvito** [comment]
Same error here OSX 10.8.2

**Comment by agirbal** [comment]
Can you try a few things:
- go to "system preferences / security and privacy / General"
  Make sure that "allow applications downloaded from" is set to "anywhere".
- It could also be that you have a case-sensitive file system.
  Run "diskutil list /" from the command line and see if it says case-sensitive.

One workaround is to right-click on the file, select Show Package Contents, then go to Contents -> Resources -> Java. Then, just open using jar. You can make an alias to this for easy access if you want.

**Comment by agirbal** [comment]
should work from above comment

**Comment by Ognian** [comment]
Still not working, when trying via command line:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/edgytech/swingfast/Application
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Caused by: java.lang.ClassNotFoundException: com.edgytech.swingfast.Application
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by Ognian** [comment]
Only way to start for the moment is to download the linux version and start via command line.
Doesn't look as nice as it could be but it works.
