### ISSUE TITLE
cannot import from a csv file

### ISSUE THREAD

**Issue by agirbal** [agirbal/umongo#87]
com.mongodb.util.JSONParseException: 
Kristina
^
    at com.mongodb.util.JSONParser.parse(JSON.java:381)
    at com.mongodb.util.JSONParser.parse(JSON.java:328)
    at com.mongodb.util.JSON.parse(JSON.java:287)
    at com.mongodb.util.JSON.parse(JSON.java:272)
    at com.edgytech.umongo.ExportFile$ExportFileInputStream.readObject(ExportFile.java:213)
    at com.edgytech.umongo.ExportFile$ExportFileInputStream$ExportFileIterator.next(ExportFile.java:152)
    at com.edgytech.umongo.ExportFile$ExportFileInputStream$ExportFileIterator.next(ExportFile.java:137)
    at com.edgytech.umongo.DocView$2.doRun(DocView.java:319)
    at com.edgytech.umongo.DbJob$1.doInBackground(DbJob.java:61)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:277)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at javax.swing.SwingWorker.run(SwingWorker.java:316)
    at com.edgytech.swingfast.ScalableThreadPool$ScalableThreadpoolWorker.run(ScalableThreadPool.java:48)
    at java.lang.Thread.run(Thread.java:680)

**Comment by agirbal** [comment]
this was just because the string values must be enclosed in quotes, not a bug
